apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: thermostat
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: thermostat
spec:
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: https://<my-repo>
      ref: feature/img-build
    contextDir: thermostat-service
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: thermostat:latest