apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{ include "thermostat-mysql.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "thermostat-mysql.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    role: primary
  ports:
    - name: mysql
      port: {{ .Values.service.port }}
      targetPort: mysql