apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
spec:
  serviceName: {{ .Release.Name }}
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "thermostat-mysql.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      role: primary
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "thermostat-mysql.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        role: primary
    spec:
      containers:
        - name: mysql
          image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag | quote }}
          ports:
            - name: mysql
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef: { name: {{ .Values.secret.name | quote }}, key: MYSQL_ROOT_PASSWORD }
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef: { name: {{ .Values.secret.name | quote }}, key: MYSQL_PASSWORD }
            - name: MYSQL_REPLICATION_PASSWORD
              valueFrom:
                secretKeyRef: { name: {{ .Values.secret.name | quote }}, key: MYSQL_REPLICATION_PASSWORD }
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database | quote }}
            - name: MYSQL_USER
              value: {{ .Values.mysql.user | quote }}
            - name: TZ
              value: {{ .Values.mysql.timezone | quote }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: {{ .Values.persistence.storageClassName | quote }}
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}